"""
Copyright (c) 2026, Motion-Craft Technology All rights reserved.

Author:
    Subin. Gopi (subing85@gmail.com).

Module:
    ./materials/gl_ocio_shader.py

Description:
    OpenColorIO GPU shader integration.

    This module provides a wrapper around OpenColorIO's GPU processing pipeline and dynamically
    generates GLSL fragment shaders for real-time color management inside the Viewline OpenGL viewer.

Responsibilities:
    * Build GPU shaders from an OpenColorIO processor.
    * Generate GLSL fragment shaders with embedded OCIO code.
    * Manage shader compilation and lifecycle.
    * Provide a simplified API for shader uniform updates.
    * Bridge OpenColorIO GPU processors with OpenGL rendering.

Features:
    * Automatic GPU shader extraction from OCIO.
    * Dynamic GLSL shader generation.
    * Uses OpenGL 4.0 GLSL backend.
    * Supports display transforms.
    * Uniform helper methods.
    * Encapsulates OpenGL shader management.

Architecture:
    OCIO Processor
           │
           ▼
    GPU Processor
           │
           ▼
    Shader Description
           │
           ▼
    Generated GLSL Fragment Shader
           │
           ▼
        GLShader
           │
           ▼
      OpenGL Rendering

Nodes:
    OCIOShader
        ├── build()
        ├── create_fragment_shader()
        ├── bind()
        ├── release()
        ├── destroy()
        └── Uniform helper methods
"""

from __future__ import absolute_import

from PyOpenColorIO import GpuShaderDesc
from PyOpenColorIO import GpuLanguage

from viewline import resources

from .gl_shader import GLShader


class OCIOShader(object):
    """
    OpenColorIO GPU shader wrapper.

    Builds OpenGL shader programs directly from an OpenColorIO processor and exposes convenience methods for shader usage.

    Responsibilities:
        * Build GPU shaders.
        * Generate fragment shader source.
        * Manage shader lifetime.
        * Forward uniform operations.

    Attributes:
        processor:
            OpenColorIO processor.

        gpu_processor:
            GPU optimized processor.

        shader (GLShader):
            Internal OpenGL shader wrapper.

        input_space:
            Current input color space.

        display:
            Active display.

        view:
            Active display view.
    """

    def __init__(self, config_path):
        """
        Initialize the OCIO shader.

        Args:
            config_path (str):
                OCIO configuration path.
                Reserved for future initialization.

        Returns:
            None
        """

        # OCIO processor
        self.processor = None

        # GPU processor
        self.gpu_processor = None

        # OpenGL shader wrapper
        self.shader = GLShader()

        # Current input colorspace
        self.input_space = None

        # Active display
        self.display = None

        # Active view
        self.view = None

    def build(self, ocio_processor):
        """
        Build an OpenGL shader from an OCIO processor.

        The processor is converted into GPU shader code which is then combined with the application's fragment shader template.

        Args:
            ocio_processor:
                OpenColorIO display processor.

        Returns:
            None
        """

        # Create GPU processor
        self.gpu_processor = ocio_processor.get_default_GPU_processor()

        # Create shader description
        shader_desc = GpuShaderDesc.CreateShaderDesc()

        # GLSL 4.0 backend
        shader_desc.setLanguage(GpuLanguage.GPU_LANGUAGE_GLSL_4_0)

        # OCIO function name
        shader_desc.setFunctionName("OCIODisplay")

        # Extract generated GLSL
        self.gpu_processor.extractGpuShaderInfo(shader_desc)

        # Build fragment shader
        fragment = self.create_fragment_shader(shader_desc.getShaderText())

        # Load vertex shader
        vertex_shader = resources.readVertexShader("display")

        # Compile shader program
        self.shader.compile(vertex_shader, fragment)

    def create_fragment_shader(self, ocio_shader):
        """Generate the final GLSL fragment shader.

        This method combines the OpenColorIO generated GLSL code with the application's fragment shader template. The resulting
        shader samples the input texture, applies the OCIO display transform, and outputs the transformed color.

        Args:
            ocio_shader (str):
                GLSL source code generated by OpenColorIO.

        Returns:
            str:
                Complete GLSL fragment shader source.
        """

        # Build the fragment shader source.
        codes = [
            "#version 330 core\n",
            # Texture coordinates from the vertex shader.
            "in vec2 uv;\n",
            # Final output color.
            "out vec4 FragColor;\n",
            # Input image texture.
            "uniform sampler2D imageTexture;\n",
            # Generated OpenColorIO shader code.
            f"{ocio_shader}\n",
            # Fragment shader entry point.
            "void main()\n",
            "{{",
            # Sample the source image.
            "\tvec4 color = texture(",
            "\t\timageTexture,",
            "\t\tuv",
            "\t);\n",
            # Apply the OCIO display transform.
            "\tcolor = OCIODisplay(color);\n",
            # Debug color modification (optional).
            # "\tcolor.rgb *= vec3(0.0, 1.0, 0.0);",
            # Write the final pixel color.
            "\tFragColor = color;",
            "}}",
        ]

        # Return the complete shader source.
        return "\n".join(codes)

    def bind(self):
        """Activate the OCIO shader program.

        Makes the internal OpenGL shader the active program for subsequent rendering operations.

        Returns:
            None
        """

        # Bind the internal shader.
        self.shader.bind()

    def release(self):
        """Deactivate the OCIO shader program.

        Restores OpenGL to having no active shader program.

        Returns:
            None
        """

        # Release the internal shader.
        self.shader.release()

    def destroy(self):
        """Release all OpenGL shader resources.

        Frees the compiled shader program and associated OpenGL resources owned by this OCIO shader.

        Returns:
            None
        """

        # Destroy the internal shader.
        self.shader.destroy()

    def uniform_location(self, name):
        """Return the location of a shader uniform.

        This is a convenience wrapper around the internal
        :class:`GLShader` implementation.

        Args:
            name (str):
                Uniform variable name.

        Returns:
            int:
                OpenGL uniform location.
        """

        # Query the uniform location from the internal shader.
        return self.shader.uniform_location(name)

    def set_uniform_int(self, name, value):
        """Upload an integer uniform.

        Args:
            name (str):
                Uniform variable name.

            value (int):
                Integer value.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_int(name, value)

    def set_uniform_float(self, name, value):
        """Upload a floating-point uniform.

        Args:
            name (str):
                Uniform variable name.

            value (float):
                Floating-point value.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_float(name, value)

    def set_uniform_vec2(self, name, x, y):
        """Upload a two-component vector uniform.

        Args:
            name (str):
                Uniform variable name.

            x (float):
                X component.

            y (float):
                Y component.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_vec2(name, x, y)

    def set_uniform_vec3(self, name, x, y, z):
        """Upload a three-component vector uniform.

        Args:
            name (str):
                Uniform variable name.

            x (float):
                X component.

            y (float):
                Y component.

            z (float):
                Z component.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_vec3(name, x, y, z)

    def set_uniform_vec4(self, name, value):
        """Upload a four-component vector uniform.

        Args:
            name (str):
                Uniform variable name.

            value (tuple[float, float, float, float]):
                RGBA or generic vec4 values.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_vec4(name, value)

    def set_uniform_mat4(self, name, matrix):
        """Upload a 4×4 matrix uniform.

        This method is typically used for transformation,
        projection, or view matrices.

        Args:
            name (str):
                Uniform variable name.

            matrix:
                4×4 matrix compatible with OpenGL.

        Returns:
            None
        """

        # Forward the uniform to the internal shader.
        self.shader.set_uniform_mat4(name, matrix)


if __name__ == "__main__":
    pass
